name: "Update GitHub Stats"

on:
  schedule:
    - cron: '0 0 * * *'  # run daily at midnight UTC
  workflow_dispatch:

jobs:
  update-stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate GitHub Stats
        uses: noahsr/github-readme-stats-action@v2
        with:
          username: Tumaini98
          token: ${{ secrets.GITHUB_TOKEN }}
          cards: stats, top-langs
          output_dir: profile
          commit_message: "chore: update GitHub stats"
